### ISSUE TITLE
🏴‍☠️ Remove type piracy 🏴‍☠️

### ISSUE THREAD

**Issue by odow** [osqp/OSQP.jl#101]
Please don't do this:
https://github.com/osqp/OSQP.jl/blob/763ad7f56bee6bbc542bff1b4a201bc69f10aafb/test/MOI_wrapper.jl#L56-L61

Not sure why it's implemented, but we're considering something similar: https://github.com/jump-dev/MathOptInterface.jl/issues/1310

**Comment by blegat** [comment]
This is the reason, note that the same issue is mentioned in the comment line 56.
