### ISSUE TITLE
Should P be upper triangular

### ISSUE THREAD

**Issue by govindchari** [osqp/OSQP.jl#124]
I am solving a problem using both the C interface and OSQP.jl.

In the C interface I only pass in the upper triangular portion of P as required. 

The only way I can get my C solution and OSQP.jl solution to match is if I only pass in the upper triangular part of P into OSQP.jl. 

This is contradictory to how some of the tests in the test directory are written (specifically primal_infeasibility.jl where an arbitrary symmetric matrix is passed in as opposed to just the upper triangular portion.

What is the correct way to pass P into OSQP.jl? If only the upper triangular part needs to be passed it would be good to call this out in the documentation.

**Comment by imciner2** [comment]
What is the structure of P you are using? There is code to take a matrix an get the upper triangular component if it isn't already upper triangular, but there is a bug in it: https://github.com/osqp/OSQP.jl/issues/93.

**Comment by govindchari** [comment]
Ah I see. It turns out that I messed up something in my end. I had an upper triangular matrix which I made a symmetric matrix as follows:

P=P'+P 

but that double counts the main diagonal and I should have done:

P=P'+P-Diagonal(P)

**Comment by imciner2** [comment]
Glad to hear you found the problem. I'll go ahead and close this since it isn't in the OSQP.jl code.
