### ISSUE TITLE
Implement MOI.NumberOfThreads

### ISSUE THREAD

**Issue by blegat** [osqp/OSQP.jl#65]

**Comment by imciner2** [comment]
@blegat  What exactly needs to be implemented here? OSQP is written as a single-threaded solver, so we can't use any user-settable thread settings.

**Comment by odow** [comment]
This can be closed. Supporting `NumberOfThreads` is optional, and only needed for solvers which support it.

**Comment by imciner2** [comment]
Thanks. Then we don't need to support it right now.
