### ISSUE TITLE
OSQP v0.6.0 can't be installed

### ISSUE THREAD

**Issue by jd-lara** [osqp/OSQP.jl#96]
The link for the OSQP version 0.6.0 is broken 

```
ERROR: Error building `OSQP`: 
ERROR: LoadError: HTTP/1.1 403 Forbidden while requesting https://dl.bintray.com/bstellato/generic/OSQP/0.6.0/osqp-0.6.0-linux64.tar.gz.sha256
```

This is relevant since #94 is still a problem.

**Comment by odow** [comment]
Is this still relevant? We now use OSQP_jll on all platforms.

**Comment by imciner2** [comment]
Bintray closed down a long time ago, so we had to switch from it. 0.6.1 and above should work properly with the jll.
